### ISSUE TITLE
Мамочки, это что, жс??

### ISSUE THREAD

**Issue by 12kot** [Asya0Anastasiya/ChatBackend#1]
Докатились...
![sticker](https://github.com/Asya0Anastasiya/ChatBackend/assets/74432402/2321d6d7-5c8c-4a35-b5ff-dd0ec2d32278)

**Comment by Asya0Anastasiya** [comment]
А что Вы имеете против, голубчик?

**Comment by 12kot** [comment]
> А что Вы имеете против, голубчик?

Конкуренты!!

**Comment by Asya0Anastasiya** [comment]
я шарпы на джс не меняю

**Comment by 12kot** [comment]
> я шарпы на джс не меняю

Посмотрим.. посмотрим

**Comment by Asya0Anastasiya** [comment]
даже не пытайся меня в свою секту переманить

**Comment by 12kot** [comment]
> даже не пытайся меня в свою секту переманить

Здесь нет никаких сект, всё по собственному желанию и без принуждений
Надо лишь начать.. И ты сама решишь стать нашей

**Comment by Asya0Anastasiya** [comment]
тогда когда-нибудь, когда ты будешь сеньором джс-а, а я дотнета, мы на неделю поменяемся местами. И будет как в фильме ужасов

**Comment by 12kot** [comment]
> тогда когда-нибудь, когда ты будешь сеньором джс-а, а я дотнета, мы на неделю поменяемся местами. И будет как в фильме ужасов

Сомнительное предложение

**Comment by Asya0Anastasiya** [comment]
> > тогда когда-нибудь, когда ты будешь сеньором джс-а, а я дотнета, мы на неделю поменяемся местами. И будет как в фильме ужасов
> 
> Сомнительное предложение

так и скажи, что импугался строгой типизации и нормального ооп

**Comment by 12kot** [comment]
Давай давай, поговори мне про типизацию. Писать на голом js какое-то извращение как по мне

**Comment by Asya0Anastasiya** [comment]
> Давай давай, поговори мне про типизацию. Писать на голом js какое-то извращение как по мне

какой индус был, такого и взяла. Был бы индус с ts, ни о каком джс и речи бы не шло

**Comment by 12kot** [comment]
Она ещё и индусов эксплуатирует..

**Comment by Asya0Anastasiya** [comment]
> Она ещё и индусов эксплуатирует..

не "эксплуатирую", а пользуюсь трудами интеллектуальной собственности, которые сами индсы радушно выставили в открытый доступ. За что им и кланяюсь
